# Generated by Django 4.2.27 on 2025-12-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='금액')),
                ('transation_type', models.CharField(choices=[('income', '소득'), ('expense', '지출')], max_length=10, verbose_name='유형')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
